#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions

gmsh -3 mesh.geo -format msh2 -o mesh.msh
runApplication gmshToFoam mesh.msh
runApplication checkMesh
sed -i "22c\        type            empty;" constant/polyMesh/boundary
sed -i "29c\        type            wall;" constant/polyMesh/boundary
runApplication decomposePar
mpirun -np 6 pimpleFoam -parallel # 6 はマシンごとに調整
runApplication reconstructPar -newTimes
paraFoam &
