#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

runApplication blockMesh
runApplication boxTurb
runApplication $application
# 並列化がうまくいかない
#runApplication decomposePar
#mpirun -np 6 dnsFoam -parallel
##mpirun -np 6 $application -parallel
#runApplication reconstructPar -newTimes
runApplication -s enstrophy  postProcess -func enstrophy
paraFoam &
